name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - web-build
  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python3 -m pip install pygbag==0.9.2

      - name: Build the site
        run: |
          python3 -m pygbag --PYBUILD 3.12 --ume_block 0 --template noctx.tmpl main.py


      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build/web  # Path to your build output directory (e.g., 'dist' or 'public')

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
