name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          sudo apt install ffmpeg
          python3 -m pip install pygbag==0.9.2 black

      - name: Build the site
        run: |
          wget https://github.com/electronstudio/pygbag-raylib/releases/download/v5.5.0.1/raylib-5.5.0.1-cp310-abi3-wasm32_bi_emscripten.whl
          unzip raylib-5.5.0.1-cp310-abi3-wasm32_bi_emscripten.whl
          rm raylib-5.5.0.1-cp310-abi3-wasm32_bi_emscripten.whl
          python3 -m pygbag --build --PYBUILD 3.12 --ume_block 0 --template noctx.tmpl --git main.py 

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
